export default [
    {
        id: 1,
        slug: 'golden-vase',
        image: 'pngaaa.png',
        imagetwo: 'pngaaa.png',
        imagethree: 'pngaaa.png',
        name: 'Golden vase',
        price: 100,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: ['php', 'js'],
    },
    {
        id: 2,
        slug: 'emerald-tray',
        image: 'malachite.png',
        imagetwo: 'malachite.png',
        imagethree: 'malachite.png',
        name: 'Emerald tray',
        price: 300,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: ['php', 'js'],
    },
    {
        id: 3,
        slug: 'pearl-vase',
        image: 'product_fruitst.png',
        imagetwo: 'product_fruitst.png',
        imagethree: 'product_fruitst.png',
        name: 'Pearl vase',
        price: 200,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: ['php'],
    },
    {
        id: 4,
        slug: 'set-of-paintings',
        image: 'pngwing.png',
        imagetwo: 'pngwing.png',
        imagethree: 'pngwing.png',
        name: 'Set of paintings',
        price: 250,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: [ 'js'],
        
    },
    {
        id: 5,
        slug: 'compositions',
        image: 'category_1.jpg',
        imagetwo: 'category_1.jpg',
        imagethree: 'category_1.jpg',
        name: 'Compositions',
        price: 40,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: ['php', 'js'],
    },
    {
        id: 6,
        slug: 'nature-prints',
        image: 'category_2.jpg',
        imagetwo: 'category_2.jpg',
        imagethree: 'category_2.jpg',
        name: 'Nature prints',
        price: 300,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
        tags: ['js'],
    },
    {
        id: 7,
        slug: 'abstraction',
        image: 'category_3.jpg',
        imagetwo: 'category_3.jpg',
        imagethree: 'category_3.jpg',
        name: 'Abstraction',
        price: 100,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
    },
    {
        id: 8,
        slug: 'geometry',
        image: 'category_4.jpg',
        imagetwo: 'category_4.jpg',
        imagethree: 'category_4.jpg',
        name: 'Geometry',
        price: 150,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
    },
    {
        id: 9,
        slug: 'watercolor',
        image: 'category_5.jpg',
        imagetwo: 'category_5.jpg',
        imagethree: 'category_5.jpg',
        name: 'Watercolor',
        price: 250,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
    },
    {
        id: 10,
        slug: 'print-poster',
        image: 'category_6.jpg',
        imagetwo: 'category_6.jpg',
        imagethree: 'category_6.jpg',
        name: 'Print & poster',
        price: 350,
        desc: 'Fine wooden frame with a golden edge. Includes a passe-partout. Elegantly designed to be used as a free-standing or wall hanging decoration, this box frame can hold a landscape or portrait image. Made in Italy.',
        quantity: 5,
    }
]